  - name: Move repos to backup
    shell: sudo mv /etc/yum.repos.d/*.repo /tmp

  - name: Copy localrepo
    copy: src={{ item }}.repo dest=/etc/yum.repos.d/{{ item }}.repo owner=root group=root mode=0644
    with_items:
    - localrepo
    - omsprod


  - name: cleaning task for yum
    command: yum clean all



