---
  - hosts: zabbix
    user: vagrant
    become: yes
    vars: 
      zabb_server: '{{ ansible_eth1.ipv4.address }}/zabbix'
    tasks:
      - name: Install Apache server
        yum: name=httpd state=installed
      - name: start Apache server
        service: name=httpd state=started enabled=yes

      - name: Install Zabbix Repository
        yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/zabbix-release-2.4-1.el7.noarch.rpm state=installed
      - name: Install  zabbixs and etc
        yum: pkg={{item}} state=installed
        with_items:
          - policycoreutils-python
          - libselinux-python
          - zabbix-server
          - zabbix-sender
          - zabbix-server-mysql
          - zabbix-web-mysql
          - zabbix-agent
          - zabbix-java-gateway
          - MySQL-python
          - php 
#          - pip
#      - name: Install MySQL(mariadb)
#        yum: name=mariadb-server state=installed
      - name: RUN Marriadb
        service: name=mariadb.service state=started enabled=yes
      - name: Create zabbix database
        mysql_db: name=zabbix state=present collation=utf8_bin
        register: create_zb_db
      - debug: msg={{ create_zb_db }}
      - name: Create Zabbix user and grant permissions
        mysql_user: name=zabbix password=zabbix priv=zabbix.*:ALL host=localhost state=present 
        when: create_zb_db.changed != False
      - name: Import initial schema
        mysql_db: name=zabbix state=import target={{item}}
        with_items:
          - /usr/share/doc/zabbix-server-mysql-2.4.7/create/schema.sql
          - /usr/share/doc/zabbix-server-mysql-2.4.7/create/images.sql
          - /usr/share/doc/zabbix-server-mysql-2.4.7/create/data.sql
        when: create_zb_db.changed != False     

      - name: Configure zabbix server
        template: src=zabbix_server.conf.j2 dest=/etc/zabbix/zabbix_server.conf
      - name: Configure zabbix server
        template: src=zabbix.conf.php.j2 dest=/etc/zabbix/web/zabbix.conf.php
      - name: Configure php
        template: src=php.ini.j2 dest=/etc/php.ini
#      - name: start zabbix server
 #       service: name=zabbix-server state=started enabled=yes


      - name: Configure SELinux 
        seboolean: name=httpd_can_network_connect state=yes persistent=yes
      - name: Run MariaDB
        service: name=mariadb.service state=restarted enabled=yes
      - name: Restart Zabbix Server
        service: name=zabbix-server enabled=true state=restarted 

      - name: istall pyzabbix by pip
        pip: name=pyzabbix state=present
      - name: Create host groups
        action:
          module: zabbix_group
          server_url: http://{{zabb_server}}
          login_user: Admin
          login_password: zabbix
          state: present
          host_groups:
            - Databases
            - WEBs
            - LOGserver
            - REPO
            - jenkins
            - balancer
            - ansible

      - debug: msg={{ ansible_hostname }}
      - debug: msg={{ ansible_eth1.ipv4.address }}


