---
- hosts: repo
  remote_user: root
  sudo: yes

  vars:
    download_url: "http://apache.volia.net/tomcat/tomcat-7/v7.0.68/bin/apache-tomcat-7.0.68.tar.gz"
    download_folder: /usr
    app_name: "{{download_folder}}/apache-tomcat-7.0.68"
    extra_path: "{{app_name}}/bin"
    app_archive: "{{download_folder}}/apache-tomcat-7.0.68.tar.gz"

  tasks:
  - name: Download Tomcat
    get_url: url={{download_url}} dest={{app_archive}}
    environment:
     http_proxy: http://192.168.5.103:8080

  - name: Unpack archive
    command: "tar -zxf {{app_archive}} -C {{download_folder}} creates={{app_name}}"

  - name: Set CATALINA_HOME
    lineinfile: dest=/etc/environment state=present
     regexp='^CATALINA_HOME'
     line='CATALINA_HOME="{{app_name}}"'

  - name: add {{extra_path}} to path
    lineinfile: dest=/etc/environment state=present
     backrefs=yes
     regexp='PATH=(["]*)((?!.*?{{extra_path}}).*?)(["]*)$'
     line="PATH=\1\2:{{extra_path}}\3"

  - name: starting Tomcat
    command: "{{extra_path}}/startup.sh"

















 